HYDERABAD_AREAS = [
    "Ameerpet",
    "AS Rao Nagar",
    "Attapur",
    "Bachupally",
    "Banjara Hills",
    "Begumpet",
    "Boduppal",
    "Chaitanyapuri",
    "Chandanagar",
    "Dilsukhnagar",
    "ECIL",
    "Falaknuma",
    "Financial District",
    "Gachibowli",
    "Gajularamaram",
    "Gandi Maisamma",
    "Gundlapochampally",
    "Habsiguda",
    "Hayathnagar",
    "Himayat Nagar",
    "Hitech City",
    "Jeedimetla",
    "JNTU",
    "Jubilee Hills",
    "Kachiguda",
    "Kapra",
    "Kokapet",
    "Kompally",
    "Kondapur",
    "Kothapet",
    "KPHB",
    "Kukatpally",
    "LB Nagar",
    "Madhapur",
    "Mallapur",
    "Malkajgiri",
    "Manikonda",
    "Medchal",
    "Mehdipatnam",
    "Miyapur",
    "Nagole",
    "Nacharam",
    "Nampally",
    "Narsingi",
    "Neredmet",
    "Nizampet",
    "Patancheru",
    "Peerzadiguda",
    "Pragathi Nagar",
    "Punjagutta",
    "Quthbullapur",
    "Raidurg",
    "Ramanthapur",
    "Sainikpuri",
    "Secunderabad",
    "Shamshabad",
    "SR Nagar",
    "Suchitra",
    "Suraram",
    "Tarnaka",
    "Tellapur",
    "Tolichowki",
    "Trimulgherry",
    "Uppal",
    "Vanasthalipuram",
    "Yapral",
    "Yousufguda"
]